# Generated by Django 4.0.3 on 2022-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refversions',
            name='init_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
