# Generated by Django 4.0.3 on 2022-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_refversions_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refversions',
            name='init_date',
            field=models.DateField(verbose_name='Дата начала действия'),
        ),
    ]
