# Generated by Django 4.0.3 on 2022-03-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_refversions_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elements',
            unique_together={('ref_version', 'code')},
        ),
    ]
