# Generated by Django 4.0.3 on 2022-04-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_alter_elements_code_alter_reftitles_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refversions',
            options={'ordering': ['-init_date'], 'verbose_name': 'Версии справочников', 'verbose_name_plural': 'Версии справочников'},
        ),
    ]
